"""create movies table

Revision ID: 2632d293c75b
Revises: ff6a9fb76d1e
Create Date: 2025-12-07 21:20:52.502707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2632d293c75b'
down_revision: Union[str, Sequence[str], None] = 'ff6a9fb76d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ghibli_api_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('original_title_romanised', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('rt_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('movie_banner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_director'), 'movies', ['director'], unique=False)
    op.create_index(op.f('ix_movies_ghibli_api_id'), 'movies', ['ghibli_api_id'], unique=True)
    op.create_index(op.f('ix_movies_original_title_romanised'), 'movies', ['original_title_romanised'], unique=False)
    op.create_index(op.f('ix_movies_producer'), 'movies', ['producer'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ix_movies_rt_score'), 'movies', ['rt_score'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_rt_score'), table_name='movies')
    op.drop_index(op.f('ix_movies_release_date'), table_name='movies')
    op.drop_index(op.f('ix_movies_producer'), table_name='movies')
    op.drop_index(op.f('ix_movies_original_title_romanised'), table_name='movies')
    op.drop_index(op.f('ix_movies_ghibli_api_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_director'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
