"""create favorite models

Revision ID: 28810b5d031a
Revises: 4f510bb0c1ef
Create Date: 2025-12-08 00:04:29.196069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28810b5d031a'
down_revision: Union[str, Sequence[str], None] = '4f510bb0c1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='uix_user_character_favorite')
    )
    op.create_index(op.f('ix_favorite_characters_character_id'), 'favorite_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_favorite_characters_user_id'), 'favorite_characters', ['user_id'], unique=False)
    op.create_table('favorite_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uix_user_movie_favorite')
    )
    op.create_index(op.f('ix_favorite_movies_movie_id'), 'favorite_movies', ['movie_id'], unique=False)
    op.create_index(op.f('ix_favorite_movies_user_id'), 'favorite_movies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_movies_user_id'), table_name='favorite_movies')
    op.drop_index(op.f('ix_favorite_movies_movie_id'), table_name='favorite_movies')
    op.drop_table('favorite_movies')
    op.drop_index(op.f('ix_favorite_characters_user_id'), table_name='favorite_characters')
    op.drop_index(op.f('ix_favorite_characters_character_id'), table_name='favorite_characters')
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
