"""create movie_status model

Revision ID: 4f510bb0c1ef
Revises: 32d53107c563
Create Date: 2025-12-07 23:13:41.402428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f510bb0c1ef'
down_revision: Union[str, Sequence[str], None] = '32d53107c563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('watched', 'want_to_watch', name='moviestatusenum'), nullable=False),
    sa.Column('watched_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uix_user_movie_status')
    )
    op.create_index(op.f('ix_movie_status_movie_id'), 'movie_status', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_status_user_id'), 'movie_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_status_user_id'), table_name='movie_status')
    op.drop_index(op.f('ix_movie_status_movie_id'), table_name='movie_status')
    op.drop_table('movie_status')
    # ### end Alembic commands ###
