"""create characters table

Revision ID: fd1356e2fe05
Revises: 2632d293c75b
Create Date: 2025-12-07 21:47:00.596398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1356e2fe05'
down_revision: Union[str, Sequence[str], None] = '2632d293c75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ghibli_api_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_age'), 'characters', ['age'], unique=False)
    op.create_index(op.f('ix_characters_gender'), 'characters', ['gender'], unique=False)
    op.create_index(op.f('ix_characters_ghibli_api_id'), 'characters', ['ghibli_api_id'], unique=True)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_ghibli_api_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_gender'), table_name='characters')
    op.drop_index(op.f('ix_characters_age'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###